### ISSUE TITLE
Added a folder

### ISSUE THREAD

**Issue by james-caltech** [vandanparmar/SURFcode#2]
Ok, I think I now have a vague understanding of how this works! I've added a folder with some simple linear algebra code. There seem to be a few extra files that were included in the folder that I can't see in my local folder. I guess there are there but just hidden.

**Comment by vandanparmar** [comment]
Yeah - I think using something like pycharm will add a bunch of random files. You can ignore them using a .gitignore file, but it probably isn't worth the effort!
